#####################
######## tap ########
#####################
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "romkatv/powerlevel10k"

######################
######## brew ########
######################
brew "autoconf"
brew "automake"
brew "bat"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "cmake"
brew "coreutils"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnutls"
brew "go"
brew "golangci-lint"
brew "hugo"
brew "mas"
brew "maven"
brew "openjdk@8"
brew "node"
brew "poppler"
brew "rustup-init"
brew "tmux"
brew "tree"
brew "unixodbc"
brew "wget"
brew "zsh-syntax-highlighting"
brew "romkatv/powerlevel10k/powerlevel10k"

######################
######## cask ########
######################
cask "google-chrome"
# cask "alfred" -- deprecated
cask "raycast"
cask "appcleaner"
cask "picgo"
cask "snipaste"
cask "bitwarden"
cask "rectangle"

######## terminal ########
# cask "alacritty"

####### font ########
cask "font-fira-code"
cask "font-jetbrains-mono"

######## ide/editor ########
cask "visual-studio-code"
cask "sublime-text"
cask "intellij-idea-ce"
# cask "intellij-idea-ce"
# cask "pycharm-ce"

######## notes ########
cask "zotero"
cask "logseq"
cask "obsidian"
cask "notion"

######## mas ########
# TODO (uncomment after "mas not signed in to Mac App Store" fixing.
# mas "Microsoft OneNote", id: 784801555
# mas "OneDrive", id: 823766827
# mas "RunCat", id: 1429033973
# mas "微信", id: 836500024
# mas "网易云音乐", id: 944848654
